# Generated by Django 2.2.16 on 2022-11-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Persons',
        ),
    ]
