# Generated by Django 2.2.16 on 2022-11-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='title',
        ),
    ]
